### ISSUE TITLE
conda install motus stuck in Executing transaction

### ISSUE THREAD

**Issue by dengzq1234** [motu-tool/mOTUs#87] opened 2022-02-14 12:38 UTC
Hi,
I tried to install motus via conda using the follwing command according to the tutorial 
`conda install -c bioconda motus`
but the install process stucked at the Executing transaction for a very long time so I have to stop it, and report showed

`ERROR conda.core.link:_execute(701): An error occurred while installing package 'bioconda::motus-2.1.1-py37_3'.`

I tried different motus and python versions and cross platforms but same error occured.

Thanks

**Comment by AlessioMilanese** [comment] 2022-02-14 12:48
Hi Ziqi,

While installing mOTUs, the database is downloaded (few Gb).  So it might be that it's waiting to download that?
Could you otherwise try to install through GitHub?
```
git clone https://github.com/motu-tool/mOTUs.git
cd motus
python setup.py sdist
motus downloadDB
```

We are also in the process of adding to `pip`. It should be done in a few days.

**Comment by dengzq1234** [comment] 2022-02-14 13:59
I see! Thanks Alessio!

**Comment by yhg926** [comment] 2022-08-23 12:50
Hi, I meet the same problem; and I have git clone mOTUs and  run python setup.py, here is the error reported:
python setup.py sdist
/home/ubt/miniconda3/lib/python3.9/site-packages/setuptools/dist.py:757: UserWarning: Usage of dash-separated 'description-file' will not be supported in future versions. Please use the underscore name 'description_file' instead
  warnings.warn(
running sdist
running egg_info
writing motu_profiler.egg-info/PKG-INFO
writing dependency_links to motu_profiler.egg-info/dependency_links.txt
writing entry points to motu_profiler.egg-info/entry_points.txt
writing top-level names to motu_profiler.egg-info/top_level.txt
package init file 'motus/__init__.py' not found (or not a regular file)
reading manifest file 'motu_profiler.egg-info/SOURCES.txt'
adding license file 'LICENSE'
writing manifest file 'motu_profiler.egg-info/SOURCES.txt'
running check
creating motu-profiler-3.0.3
creating motu-profiler-3.0.3/motu_profiler.egg-info
creating motu-profiler-3.0.3/motus
copying files to motu-profiler-3.0.3...
copying LICENSE -> motu-profiler-3.0.3
copying README.md -> motu-profiler-3.0.3
copying setup.cfg -> motu-profiler-3.0.3
copying setup.py -> motu-profiler-3.0.3
copying motu_profiler.egg-info/PKG-INFO -> motu-profiler-3.0.3/motu_profiler.egg-info
copying motu_profiler.egg-info/SOURCES.txt -> motu-profiler-3.0.3/motu_profiler.egg-info
copying motu_profiler.egg-info/dependency_links.txt -> motu-profiler-3.0.3/motu_profiler.egg-info
copying motu_profiler.egg-info/entry_points.txt -> motu-profiler-3.0.3/motu_profiler.egg-info
copying motu_profiler.egg-info/top_level.txt -> motu-profiler-3.0.3/motu_profiler.egg-info
copying motus/PEfiltering.py -> motu-profiler-3.0.3/motus
copying motus/UTIL_log.py -> motu-profiler-3.0.3/motus
copying motus/UTIL_log_col.py -> motu-profiler-3.0.3/motus
copying motus/append.py -> motu-profiler-3.0.3/motus
copying motus/convert_long_reads.py -> motu-profiler-3.0.3/motus
copying motus/downloadDB.py -> motu-profiler-3.0.3/motus
copying motus/map_genes_to_mOTUs.py -> motu-profiler-3.0.3/motus
copying motus/map_mOTUs_to_LGs.py -> motu-profiler-3.0.3/motus
copying motus/metaSNV_DistDiv.py -> motu-profiler-3.0.3/motus
copying motus/metaSNV_Filtering_2.0.py -> motu-profiler-3.0.3/motus
copying motus/motu_utilities.py -> motu-profiler-3.0.3/motus
copying motus/motus.py -> motu-profiler-3.0.3/motus
copying motus/msamtools_python.py -> motu-profiler-3.0.3/motus
copying motus/print_CAMI.py -> motu-profiler-3.0.3/motus
copying motus/runBWA.py -> motu-profiler-3.0.3/motus
copying motus/runBWA_for_snv.py -> motu-profiler-3.0.3/motus
copying motus/test.py -> motu-profiler-3.0.3/motus
Writing motu-profiler-3.0.3/setup.cfg
Creating tar archive
removing 'motu-profiler-3.0.3' (and everything under it)
===============
motus downloadDB
[E::main] Error: database has not been downloaded. Run setup.py before using the motus profiler

could you help with this ?

**Comment by AlessioMilanese** [comment] 2022-08-23 14:16
Can you try `pip install motu-profiler`? What does it says?

**Comment by yhg926** [comment] 2022-08-24 02:00
just can't run  motus 
(base) ubuntu@ip-172-31-36-88:~$  pip install motu-profiler
Requirement already satisfied: motu-profiler in ./miniconda3/lib/python3.9/site-packages/motu_profiler-3.0.3-py3.9.egg (3.0.3)
(base) ubuntu@ip-172-31-36-88:~$ motus downloadDB
Command 'motus' not found, did you mean:
  command 'lotus' from snap lotus (latest)
  command 'motes' from snap motes (6.3.3)
  command 'notus' from snap notus (0.5.1)
See 'snap info <snapname>' for additional versions.

**Comment by hjruscheweyh** [comment] 2022-08-24 10:35
Hi Both

You're using `pip` inside a `conda` environment. So my assumption is that you're using the local installation `pip` and not the `conda pip`. However you're using the `conda python`. So there is a disconnect on where `motus` is installed and by that cannot be found by `python`. Try to use `pip` inside `python` by using `python -m pip ...`. In this case it would be:

```
python -m pip install motu-profiler
```

**Comment by yhg926** [comment] 2022-08-24 11:55
After many tries, I have finally installed mOTUs. And I found the Version: 2.5.1 is not the latest version 3.*, so how can i update to the latest version?

**Comment by AlessioMilanese** [comment] 2022-08-24 21:41
I guess you installed with conda. You can try:
```
conda install -c bioconda motus=3.0.3
```

**Comment by yhg926** [comment] 2022-08-25 04:45
> I guess you installed with conda. You can try:
> 
> ```
> conda install -c bioconda motus=3.0.3
> ```
It works, but i still need to download DB again when runs motus. However motus downloadDB always failed(maybe due to slow network), any solution for this ?
======here is the error reported================
motus downloadDB
 ------------------------------------------------------------------------------
|                              SETUP MOTUS TOOL                                |
 ------------------------------------------------------------------------------
Download the compressed motus database (~3.5Gb)
 8%, 273 MB, 87 KB/s, 3214 seconds passedTraceback (most recent call last):
  File "/home/ubt/miniconda3/bin/motus", line 7, in <module>
    from motus.motus import main
  File "/home/ubt/miniconda3/lib/python3.9/site-packages/motus/motus.py", line 77, in <module>
    motus.downloadDB.main()
  File "/home/ubt/miniconda3/lib/python3.9/site-packages/motus/downloadDB.py", line 83, in main
    save_f(link_db, db_name)
  File "/home/ubt/miniconda3/lib/python3.9/site-packages/motus/downloadDB.py", line 45, in save_f
    urllib.request.urlretrieve(url, filename, reporthook)
  File "/home/ubt/miniconda3/lib/python3.9/urllib/request.py", line 278, in urlretrieve
    raise ContentTooShortError(
urllib.error.ContentTooShortError: <urlopen error retrieval incomplete: got only 286555128 out of 3505108629 bytes>

**Comment by AlessioMilanese** [comment] 2022-08-25 05:03
It seems it is downloading really slow (87 KB/s).
I actually had the same problem for the first time 5 days ago. 
The database is hosted on [zenodo](https://zenodo.org/record/5140350#.YwcCC_FBwbk), and apparently sometimes it is very slow.

When I tried again the day after it was downloading at 30 MB/s, and the whole database was downloaded after few minutes. Maybe you can try again in a day?
If this keep on happening, we might have to change the location of the database!

**Comment by yhg926** [comment] 2022-08-26 06:40
> It seems it is downloading really slow (87 KB/s). I actually had the same problem for the first time 5 days ago (and the download would stop also for me). The database is hosted on [zenodo](https://zenodo.org/record/5140350#.YwcCC_FBwbk), and apparently sometimes it is very slow.
> 
> When I tried again the day after it was downloading at 30 MB/s, and the whole database was downloaded after few minutes. Maybe you can try again in a day? If this keep on happening, we might have to change the location of the database!

I have tried many times to download DB these two days and all failed. I think it is better to  change the location .

**Comment by yhg926** [comment] 2022-08-29 10:50
> > I guess you installed with conda. You can try:
> > ```
> > conda install -c bioconda motus=3.0.3
> > ```
> 
> It works, but i still need to download DB again when runs motus. However motus downloadDB always failed(maybe due to slow network), any solution for this ?
> 
> ```
> motus downloadDB
>  ------------------------------------------------------------------------------
> |                              SETUP MOTUS TOOL                                |
>  ------------------------------------------------------------------------------
> Download the compressed motus database (~3.5Gb)
>  8%, 273 MB, 87 KB/s, 3214 seconds passedTraceback (most recent call last):
>   File "/home/ubt/miniconda3/bin/motus", line 7, in <module>
>     from motus.motus import main
>   File "/home/ubt/miniconda3/lib/python3.9/site-packages/motus/motus.py", line 77, in <module>
>     motus.downloadDB.main()
>   File "/home/ubt/miniconda3/lib/python3.9/site-packages/motus/downloadDB.py", line 83, in main
>     save_f(link_db, db_name)
>   File "/home/ubt/miniconda3/lib/python3.9/site-packages/motus/downloadDB.py", line 45, in save_f
>     urllib.request.urlretrieve(url, filename, reporthook)
>   File "/home/ubt/miniconda3/lib/python3.9/urllib/request.py", line 278, in urlretrieve
>     raise ContentTooShortError(
> urllib.error.ContentTooShortError: <urlopen error retrieval incomplete: got only 286555128 out of 3505108629 bytes>
> ```

I thought i have download motus3 until i saw "Version 2.6.0" when i run motus, though the motus script is under the motus-3.0.3 folder:

 python /home/ubt/miniconda3/pkgs/motus-3.0.3-pyhdfd78af_0/python-scripts/motus

Program: motus - a tool for marker gene-based OTU (mOTU) profiling
Version: 2.6.0
Reference: Milanese et al. Microbial abundance, activity and population genomic profiling with mOTUs2. Nature Communications (2019). doi: 10.1038/s41467-019-08844-4 
....
===================
my question is am i running motus3 or motus2.6.0 ?

**Comment by AlessioMilanese** [comment] 2022-08-31 12:36
yes, you have mOTUs 2.6.0. You can check also with `motus --version`

Which for me returns:
```
motus 3.0.3 on python 3.7.3
```

It might be the python version the problem? Which python version are you using?

**Comment by yhg926** [comment] 2022-08-31 14:25
Mine:
python ~/miniconda3/pkgs/motus-3.0.3-pyhdfd78af_0/python-scripts/motus --version
motus 2.6.0 on python 3.9.7.

so i still do not have motus3.0.3 ?  my install command is 
conda install -c bioconda motus=3.0.3

how can i get real  motus3.0.3  then ?

**Comment by AlessioMilanese** [comment] 2022-08-31 14:51
I'm not sure what it is going wrong, but if you do:
```
conda create -n motus3 motus=3.0.3
```

where I get:
```
The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    libblas-3.9.0              |16_osx64_openblas          13 KB  conda-forge
    libcblas-3.9.0             |16_osx64_openblas          13 KB  conda-forge
    libcxx-14.0.6              |       hccf4f1f_0         1.3 MB  conda-forge
    libgfortran-5.0.0          |10_4_0_h97931a8_25         146 KB  conda-forge
    libgfortran5-11.3.0        |      h082f757_25         1.9 MB  conda-forge
    liblapack-3.9.0            |16_osx64_openblas          13 KB  conda-forge
    libnghttp2-1.47.0          |       h5aae05b_1         875 KB  conda-forge
    libopenblas-0.3.21         |openmp_h947e540_2         9.6 MB  conda-forge
    libssh2-1.10.0             |       h47af595_3         222 KB  conda-forge
    metasnv-1.0.3              |   py39h3ddd199_4         126 KB  bioconda
    motus-3.0.3                |     pyhdfd78af_0          78 KB  bioconda
    numpy-1.23.2               |   py39h62c883e_0         6.6 MB  conda-forge
    openssl-3.0.5              |       hb81d4ab_1         2.5 MB  conda-forge
    pandas-1.4.3               |   py39hf72b562_0        11.9 MB  conda-forge
    pip-22.2.2                 |     pyhd8ed1ab_0         1.5 MB  conda-forge
    python-3.9.9               |h38b4d05_0_cpython        12.6 MB  conda-forge
    pytz-2022.2.1              |     pyhd8ed1ab_0         224 KB  conda-forge
    setuptools-65.3.0          |     pyhd8ed1ab_1         782 KB  conda-forge
    tzdata-2022c               |       h191b570_0         119 KB  conda-forge
    xz-5.2.6                   |       h775f41a_0         233 KB  conda-forge
    ------------------------------------------------------------
                                           Total:        50.7 MB
```

and here I see `motus-3.0.3` in the package list.

After installing you can do `conda activate motus3` (sometimes you need to do `source activate motus3`) to activate the environment.

And now you will have mOTUs3, which you can run just with `motus` (once the env is active).

**Comment by yhg926** [comment] 2022-08-31 14:57
Mine:
$ conda create -n motus3 motus=3.0.3
Collecting package metadata (current_repodata.json): done
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: failed

PackagesNotFoundError: The following packages are not available from current channels:

  - motus=3.0.3

Current channels:

  - https://repo.anaconda.com/pkgs/main/linux-64
  - https://repo.anaconda.com/pkgs/main/noarch
  - https://repo.anaconda.com/pkgs/r/linux-64
  - https://repo.anaconda.com/pkgs/r/noarch

To search for alternate channels that may provide the conda package you're
looking for, navigate to

    https://anaconda.org

and use the search bar at the top of the page.

**Comment by AlessioMilanese** [comment] 2022-08-31 14:59
Can you try: `conda create -c bioconda -n motus3 motus=3.0.3` ?

**Comment by yhg926** [comment] 2022-09-01 02:17
> Can you try: `conda create -c bioconda -n motus3 motus=3.0.3` ?

An unexpected error has occurred：
$ conda create -c bioconda -n motus3 motus=3.0.3
Collecting package metadata (current_repodata.json): done
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: done

## Package Plan ##

  environment location: /home/ubt/miniconda3/envs/motus3

  added / updated specs:
    - motus=3.0.3


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    bottleneck-1.3.5           |   py38h7deecbd_0         115 KB
    libdeflate-1.8             |       h7f8727e_5          51 KB
    mkl-service-2.4.0          |   py38h7f8727e_0          59 KB
    mkl_fft-1.3.1              |   py38hd3c417c_0         180 KB
    mkl_random-1.2.2           |   py38h51133e4_0         308 KB
    numexpr-2.8.3              |   py38h807cd23_0         125 KB
    numpy-1.23.1               |   py38h6c91a56_0          11 KB
    numpy-base-1.23.1          |   py38ha15fc14_0         5.6 MB
    pandas-1.4.3               |   py38h6a678d5_0         9.9 MB
    pip-22.1.2                 |   py38h06a4308_0         2.5 MB
    pyparsing-3.0.9            |   py38h06a4308_0         152 KB
    python-3.8.1               |       h0371630_1        49.5 MB
    setuptools-63.4.1          |   py38h06a4308_0         1.1 MB
    ------------------------------------------------------------
                                           Total:        69.5 MB

The following NEW packages will be INSTALLED:

  _libgcc_mutex      pkgs/main/linux-64::_libgcc_mutex-0.1-main
  _openmp_mutex      pkgs/main/linux-64::_openmp_mutex-5.1-1_gnu
  blas               pkgs/main/linux-64::blas-1.0-mkl
  bottleneck         pkgs/main/linux-64::bottleneck-1.3.5-py38h7deecbd_0
  bwa                bioconda/linux-64::bwa-0.7.17-h5bf99c6_8
  bzip2              pkgs/main/linux-64::bzip2-1.0.8-h7b6447c_0
  ca-certificates    pkgs/main/linux-64::ca-certificates-2022.07.19-h06a4308_0
  certifi            pkgs/main/linux-64::certifi-2022.6.15-py38h06a4308_0
  curl               pkgs/main/linux-64::curl-7.69.1-hbc83047_0
  htslib             bioconda/linux-64::htslib-1.9-h4da6232_3
  intel-openmp       pkgs/main/linux-64::intel-openmp-2021.4.0-h06a4308_3561
  krb5               pkgs/main/linux-64::krb5-1.17.1-h173b8e3_0
  ld_impl_linux-64   pkgs/main/linux-64::ld_impl_linux-64-2.38-h1181459_1
  libcurl            pkgs/main/linux-64::libcurl-7.69.1-h20c2e04_0
  libdeflate         pkgs/main/linux-64::libdeflate-1.8-h7f8727e_5
  libedit            pkgs/main/linux-64::libedit-3.1.20181209-hc058e9b_0
  libffi             pkgs/main/linux-64::libffi-3.2.1-hf484d3e_1007
  libgcc-ng          pkgs/main/linux-64::libgcc-ng-11.2.0-h1234567_1
  libgomp            pkgs/main/linux-64::libgomp-11.2.0-h1234567_1
  libssh2            pkgs/main/linux-64::libssh2-1.10.0-h8f2d780_0
  libstdcxx-ng       pkgs/main/linux-64::libstdcxx-ng-11.2.0-h1234567_1
  metasnv            bioconda/linux-64::metasnv-1.0.3-h230ddbb_2
  mkl                pkgs/main/linux-64::mkl-2021.4.0-h06a4308_640
  mkl-service        pkgs/main/linux-64::mkl-service-2.4.0-py38h7f8727e_0
  mkl_fft            pkgs/main/linux-64::mkl_fft-1.3.1-py38hd3c417c_0
  mkl_random         pkgs/main/linux-64::mkl_random-1.2.2-py38h51133e4_0
  motus              bioconda/noarch::motus-3.0.3-pyhdfd78af_0
  ncurses            pkgs/main/linux-64::ncurses-6.1-he6710b0_1
  numexpr            pkgs/main/linux-64::numexpr-2.8.3-py38h807cd23_0
  numpy              pkgs/main/linux-64::numpy-1.23.1-py38h6c91a56_0
  numpy-base         pkgs/main/linux-64::numpy-base-1.23.1-py38ha15fc14_0
  openssl            pkgs/main/linux-64::openssl-1.1.1q-h7f8727e_0
  packaging          pkgs/main/noarch::packaging-21.3-pyhd3eb1b0_0
  pandas             pkgs/main/linux-64::pandas-1.4.3-py38h6a678d5_0
  perl               pkgs/main/linux-64::perl-5.26.2-h14c3975_0
  pip                pkgs/main/linux-64::pip-22.1.2-py38h06a4308_0
  pyparsing          pkgs/main/linux-64::pyparsing-3.0.9-py38h06a4308_0
  python             pkgs/main/linux-64::python-3.8.1-h0371630_1
  python-dateutil    pkgs/main/noarch::python-dateutil-2.8.2-pyhd3eb1b0_0
  pytz               pkgs/main/linux-64::pytz-2022.1-py38h06a4308_0
  readline           pkgs/main/linux-64::readline-7.0-h7b6447c_5
  samtools           bioconda/linux-64::samtools-1.9-h10a08f8_12
  setuptools         pkgs/main/linux-64::setuptools-63.4.1-py38h06a4308_0
  six                pkgs/main/noarch::six-1.16.0-pyhd3eb1b0_1
  sqlite             pkgs/main/linux-64::sqlite-3.31.1-h7b6447c_0
  tk                 pkgs/main/linux-64::tk-8.6.12-h1ccaba5_0
  wheel              pkgs/main/noarch::wheel-0.37.1-pyhd3eb1b0_0
  xz                 pkgs/main/linux-64::xz-5.2.5-h7f8727e_1
  zlib               pkgs/main/linux-64::zlib-1.2.12-h7f8727e_2


Proceed ([y]/n)? y


Downloading and Extracting Packages
mkl_random-1.2.2     | 308 KB    | ################################################################################################# | 100%
numexpr-2.8.3        | 125 KB    | ################################################################################################# | 100%
mkl_fft-1.3.1        | 180 KB    | ################################################################################################# | 100%
pip-22.1.2           | 2.5 MB    | ################################################################################################# | 100%
bottleneck-1.3.5     | 115 KB    | ################################################################################################# | 100%
libdeflate-1.8       | 51 KB     | ################################################################################################# | 100%
pandas-1.4.3         | 9.9 MB    | ################################################################################################# | 100%
pyparsing-3.0.9      | 152 KB    | ################################################################################################# | 100%
python-3.8.1         | 49.5 MB   | ################################################################################################# | 100%
numpy-1.23.1         | 11 KB     | ################################################################################################# | 100%
setuptools-63.4.1    | 1.1 MB    | ################################################################################################# | 100%
numpy-base-1.23.1    | 5.6 MB    | ################################################################################################# | 100%
mkl-service-2.4.0    | 59 KB     | ################################################################################################# | 100%
Preparing transaction: done
Verifying transaction: done
Executing transaction: done
#
# To activate this environment, use
#
#     $ conda activate motus3
#
# To deactivate an active environment, use
#
#     $ conda deactivate

Retrieving notices: ...working... failed

# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "/home/ubt/miniconda3/lib/python3.9/site-packages/urllib3/connectionpool.py", line 699, in urlopen
        httplib_response = self._make_request(
      File "/home/ubt/miniconda3/lib/python3.9/site-packages/urllib3/connectionpool.py", line 382, in _make_request
        self._validate_conn(conn)
      File "/home/ubt/miniconda3/lib/python3.9/site-packages/urllib3/connectionpool.py", line 1010, in _validate_conn
        conn.connect()
      File "/home/ubt/miniconda3/lib/python3.9/site-packages/urllib3/connection.py", line 411, in connect
        self.sock = ssl_wrap_socket(
      File "/home/ubt/miniconda3/lib/python3.9/site-packages/urllib3/util/ssl_.py", line 449, in ssl_wrap_socket
        ssl_sock = _ssl_wrap_socket_impl(
      File "/home/ubt/miniconda3/lib/python3.9/site-packages/urllib3/util/ssl_.py", line 493, in _ssl_wrap_socket_impl
        return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
      File "/home/ubt/miniconda3/lib/python3.9/ssl.py", line 500, in wrap_socket
        return self.sslsocket_class._create(
      File "/home/ubt/miniconda3/lib/python3.9/ssl.py", line 1040, in _create
        self.do_handshake()
      File "/home/ubt/miniconda3/lib/python3.9/ssl.py", line 1309, in do_handshake
        self._sslobj.do_handshake()
    ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129)

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "/home/ubt/miniconda3/lib/python3.9/site-packages/requests/adapters.py", line 439, in send
        resp = conn.urlopen(
      File "/home/ubt/miniconda3/lib/python3.9/site-packages/urllib3/connectionpool.py", line 783, in urlopen
        return self.urlopen(
      File "/home/ubt/miniconda3/lib/python3.9/site-packages/urllib3/connectionpool.py", line 783, in urlopen
        return self.urlopen(
      File "/home/ubt/miniconda3/lib/python3.9/site-packages/urllib3/connectionpool.py", line 783, in urlopen
        return self.urlopen(
      File "/home/ubt/miniconda3/lib/python3.9/site-packages/urllib3/connectionpool.py", line 755, in urlopen
        retries = retries.increment(
      File "/home/ubt/miniconda3/lib/python3.9/site-packages/urllib3/util/retry.py", line 574, in increment
        raise MaxRetryError(_pool, url, error or ResponseError(cause))
    urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='conda.anaconda.org', port=443): Max retries exceeded with url: /bioconda/notices.json (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129)')))

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "/home/ubt/miniconda3/lib/python3.9/site-packages/conda/exceptions.py", line 1125, in __call__
        return func(*args, **kwargs)
      File "/home/ubt/miniconda3/lib/python3.9/site-packages/conda/cli/main.py", line 86, in main_subshell
        exit_code = do_call(args, p)
      File "/home/ubt/miniconda3/lib/python3.9/site-packages/conda/cli/conda_argparse.py", line 93, in do_call
        return getattr(module, func_name)(args, parser)
      File "/home/ubt/miniconda3/lib/python3.9/site-packages/conda/notices/core.py", line 75, in wrapper
        display_notices(
      File "/home/ubt/miniconda3/lib/python3.9/site-packages/conda/notices/core.py", line 39, in display_notices
        channel_notice_responses = http.get_notice_responses(channel_name_urls, silent=silent)
      File "/home/ubt/miniconda3/lib/python3.9/site-packages/conda/notices/http.py", line 36, in get_notice_responses
        return tuple(
      File "/home/ubt/miniconda3/lib/python3.9/site-packages/conda/notices/http.py", line 39, in <genexpr>
        (
      File "/home/ubt/miniconda3/lib/python3.9/concurrent/futures/_base.py", line 608, in result_iterator
        yield fs.pop().result()
      File "/home/ubt/miniconda3/lib/python3.9/concurrent/futures/_base.py", line 445, in result
        return self.__get_result()
      File "/home/ubt/miniconda3/lib/python3.9/concurrent/futures/_base.py", line 390, in __get_result
        raise self._exception
      File "/home/ubt/miniconda3/lib/python3.9/concurrent/futures/thread.py", line 52, in run
        result = self.fn(*self.args, **self.kwargs)
      File "/home/ubt/miniconda3/lib/python3.9/site-packages/conda/notices/http.py", line 42, in <lambda>
        lambda args: get_channel_notice_response(*args), url_and_names
      File "/home/ubt/miniconda3/lib/python3.9/site-packages/conda/notices/cache.py", line 37, in wrapper
        return_value = func(url, name)
      File "/home/ubt/miniconda3/lib/python3.9/site-packages/conda/notices/http.py", line 58, in get_channel_notice_response
        resp = session.get(url, allow_redirects=False, timeout=5)  # timeout: connect, read
      File "/home/ubt/miniconda3/lib/python3.9/site-packages/requests/sessions.py", line 555, in get
        return self.request('GET', url, **kwargs)
      File "/home/ubt/miniconda3/lib/python3.9/site-packages/requests/sessions.py", line 542, in request
        resp = self.send(prep, **send_kwargs)
      File "/home/ubt/miniconda3/lib/python3.9/site-packages/requests/sessions.py", line 655, in send
        r = adapter.send(request, **kwargs)
      File "/home/ubt/miniconda3/lib/python3.9/site-packages/requests/adapters.py", line 514, in send
        raise SSLError(e, request=request)
    requests.exceptions.SSLError: HTTPSConnectionPool(host='conda.anaconda.org', port=443): Max retries exceeded with url: /bioconda/notices.json (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129)')))

`$ /home/ubt/miniconda3/bin/conda create -c bioconda -n motus3 motus=3.0.3`

  environment variables:
                 CIO_TEST=<not set>
   CONDA_BACKUP_JAVA_HOME=:-
CONDA_BACKUP_JAVA_LD_LIBRARY_PATH=:-
        CONDA_DEFAULT_ENV=base
                CONDA_EXE=/home/ubt/miniconda3/bin/conda
             CONDA_PREFIX=/home/ubt/miniconda3
    CONDA_PROMPT_MODIFIER=(base)
         CONDA_PYTHON_EXE=/home/ubt/miniconda3/bin/python
               CONDA_ROOT=/home/ubt/miniconda3
              CONDA_SHLVL=1
           CURL_CA_BUNDLE=<not set>
     JAVA_LD_LIBRARY_PATH=/home/ubt/miniconda3/lib/server
                     PATH=/home/ubt/miniconda3/bin:/home/ubt/work1/tools/lemmi-v2/workflow/scrip
                          ts:/home/ubt/miniconda3/bin:/home/ubt/miniconda3/condabin:/home/ubt/bi
                          n:/mnt/sda/tools/emsdk:/mnt/sda/tools/emsdk/upstream/emscripten:/mnt/s
                          da/tools/emsdk/node/14.18.2_64bit/bin:/usr/local/sbin:/usr/local/bin:/
                          usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/ho
                          me/ubt/.local/bin
       REQUESTS_CA_BUNDLE=<not set>
            SSL_CERT_FILE=<not set>

     active environment : base
    active env location : /home/ubt/miniconda3
            shell level : 1
       user config file : /home/ubt/.condarc
 populated config files : /home/ubt/.condarc
          conda version : 4.14.0
    conda-build version : not installed
         python version : 3.9.7.final.0
       virtual packages : __linux=5.13.0=0
                          __glibc=2.34=0
                          __unix=0=0
                          __archspec=1=x86_64
       base environment : /home/ubt/miniconda3  (writable)
      conda av data dir : /home/ubt/miniconda3/etc/conda
  conda av metadata url : None
           channel URLs : https://conda.anaconda.org/bioconda/linux-64
                          https://conda.anaconda.org/bioconda/noarch
                          https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /home/ubt/miniconda3/pkgs
                          /home/ubt/.conda/pkgs
       envs directories : /home/ubt/miniconda3/envs
                          /home/ubt/.conda/envs
               platform : linux-64
             user-agent : conda/4.14.0 requests/2.25.1 CPython/3.9.7 Linux/5.13.0-52-generic ubuntu/21.10 glibc/2.34
                UID:GID : 1000:1000
             netrc file : None
           offline mode : False


An unexpected error has occurred. Conda has prepared the above report.

If submitted, this report will be used by core maintainers to improve
future releases of conda.
Would you like conda to send this report to the core maintainers?

[y/N]:
Timeout reached. No report sent.

**Comment by AlessioMilanese** [comment] 2022-09-01 09:14
I'm not sure what is happening there. But, since you have a working mOTUs 2.6 version, you can download a database (with mOTUs version 3) that I prepared for you in https://sunagawalab.ethz.ch/share/TEMP_MOTUS_DB/. 

You can download with:
```
wget https://sunagawalab.ethz.ch/share/TEMP_MOTUS_DB/motus-db_3.0.2.tar.gz
```

and unzip with:
```
tar -xvzf motus-db_3.0.2.tar.gz
```

Then you should be able to run it with:
```
python /home/ubt/miniconda3/pkgs/motus-3.0.3-pyhdfd78af_0/python-scripts/motus -db /path/to/the/downloaded/db/
```

where you should replace `/path/to/the/downloaded/db/` with the database repository that you just unzipped.

**Comment by yhg926** [comment] 2022-09-01 09:23
I have already downloaded motus-db_3.0.1.tar.gz previously, I am just not
sure if mOTUs 2.6  and mOTUs 3 will produce the same results if the
database is the same?


Alessio Milanese ***@***.***> 于2022年9月1日周四 17:14写道：

**Comment by AlessioMilanese** [comment] 2022-09-01 09:29
There were only minor changes between mOTUs 2.6 and mOTUs 3.0.
The naming of the mOTUs changed, and the taxonomy improved with version 3.0.1. But for 3.0.1 and 3.0.2 and 3.0.3 the results are the same.

So if you have mOTUs 2.6, you can use the database from 3.0.1 to run mOTUs.

**Closed** 2022-09-15 07:56 UTC
Labels: help wanted
